#!/bin/sh

pub_failed=1
query_failed=1
authz_location=$PWD/cms_authz

function finish_txn {
  if [ $pub_failed -eq 1 ]; then
    cvmfs_server abort -f
    exit 1
  elif [ $query_failed -eq 1 ]; then
    cvmfs_server publish -F $authz_location -X cms.osgstorage.org
    exit 2
  else
    exec cvmfs_server publish -F $authz_location -X cms.osgstorage.org
  fi
}

echo "Starting CMS data update at `date`"

voms-proxy-init -rfc -valid 168:00 -voms cms -out $PWD/cms_credential

echo "Aborting any old transaction."
cvmfs_server abort -f cms.osgstorage.org
echo "Starting new transaction."
set -e
cvmfs_server transaction cms.osgstorage.org
set +e
trap finish_txn EXIT SIGHUP SIGINT SIGTERM

# Make sure python always dumps out any debugging
export PYTHONUNBUFFERED=1

# For now, publish even on failure - we want to publish partial progress.
# May revisit later.
pub_failed=0
export X509_USER_PROXY=$PWD/cms_credential
pushd ~

cvmfs_sync root://red-gridftp12.unl.edu//store/relval/,\
           gsiftp://red-gridftp.unl.edu//user/uscms01/pnfs/unl.edu/data4/cms/store/relval/ \
           /cvmfs/cms.osgstorage.org/store/relval/ \
           --concurrency 180 \
           --ignore '*RemoteStageOutTest*'

cvmfs_sync root://red-gridftp12.unl.edu//store/mc/,\
           gsiftp://red-gridftp.unl.edu//user/uscms01/pnfs/unl.edu/data4/cms/store/mc/ \
           /cvmfs/cms.osgstorage.org/store/mc/ \
           --concurrency 180 \
           --ignore '*RemoteStageOutTest*'

cvmfs_sync root://red-gridftp12.unl.edu//store/data/,\
           gsiftp://red-gridftp.unl.edu//user/uscms01/pnfs/unl.edu/data4/cms/store/data/ \
           /cvmfs/cms.osgstorage.org/store/data/ \
           --concurrency 180 \
           --ignore '*RemoteStageOutTest*'

cvmfs_sync root://red-gridftp12.unl.edu//store/user/,\
           gsiftp://red-gridftp.unl.edu//user/uscms01/pnfs/unl.edu/data4/cms/store/user/ \
           /cvmfs/cms.osgstorage.org/store/user/ \
           --concurrency 180 \
           --ignore '*RemoteStageOutTest*'

popd

