#!/bin/sh

pub_failed=1
query_failed=1
authz_location=$PWD/ligo_authz

function finish_txn {
  if [ $pub_failed -eq 1 ]; then
    cvmfs_server abort -f
    exit 1
  elif [ $query_failed -eq 1 ]; then
    echo "Failing publish because authentication query failed"
    echo "Is the LIGO authentication servers working and responding to requests?"
    exit 2
  else
    cvmfs_server publish -F $authz_location -X ligo.osgstorage.org
    exit_result=$?
    rm $tmp_file
    exit $exit_result
  fi
}

echo "Starting LIGO frame data update at `date`"

voms-proxy-init -rfc -valid 168:00
if `voms-proxy-info --exists --valid 1:0`; then
  voms-proxy-info -all
  echo "Valid proxy!"
  # Proxy is valid but VOMS extension is about to expire.
  if [ `voms-proxy-info -actimeleft` -lt 3600 ]; then
    echo "Generating new VOMS extensions."
    #voms-proxy-init -voms osg:/osg/ligo -rfc -valid 168:00 -noregen
    voms-proxy-init -rfc -valid 168:00
  fi
else
  echo "Proxy has expired."
  exit 1
fi

# Generate a new authz list which we will use for publication
tmp_file=`mktemp`
if `/usr/libexec/cvmfs-sync/ligo-auth-gen $tmp_file -w ligo_authz`; then
  echo "Successfully updated LIGO user list."
  query_failed=0
  authz_location=$tmp_file
else
  echo "Failed to update LIGO user list, so exiting"
  echo "Is the LIGO authentication servers working and responding to requests?"
  query_failed=1
  exit 2
fi

# Periodically, we'll get a "ligo.osgstorage.org is not based on the newest published revision";
# this seems to clear it up.
echo "Aborting any old transaction."
cvmfs_server abort -f ligo.osgstorage.org
echo "Starting new transaction."
set -e
cvmfs_server transaction ligo.osgstorage.org
set +e
trap finish_txn EXIT ERR SIGHUP SIGINT SIGTERM

# We want to have python print out debug statements as soon as possible - helps with debugging deadlocks.
export PYTHONUNBUFFERED=1

# For now, publish even on failure - we want to publish partial progress.
# May revisit later.
pub_failed=0
pushd ~
cvmfs_sync -n 15 root://xrootd-local.unl.edu//user/ligo/frames/O2 /cvmfs/ligo.osgstorage.org/frames/O2 --ignore '*.tmp'
cvmfs_sync -n 15 root://xrootd-local.unl.edu//user/ligo/frames/AdVirgo /cvmfs/ligo.osgstorage.org/frames/AdVirgo --ignore '*.tmp'
cvmfs_sync -n 15 root://xrootd-local.unl.edu//user/ligo/pycbc /cvmfs/ligo.osgstorage.org/pycbc --ignore '*.tmp'
popd

