#!/bin/sh

pub_failed=1

function finish_txn {
  if [ $pub_failed -eq 1 ]; then
    cvmfs_server abort -f
    exit 1
  else
    exec cvmfs_server publish -X mu2e.osgstorage.org
  fi
}

echo "Starting mu2e public data update at `date`"

# Periodically, we'll get a "mu2e.osgstorage.org is not based on the newest published revision";
# this seems to clear it up.
cvmfs_server abort -f mu2e.osgstorage.org
set -e
cvmfs_server transaction mu2e.osgstorage.org
set +e

trap finish_txn EXIT ERR SIGHUP SIGINT SIGTERM

# For now, publish even on failure - we want to publish partial progress.
# May revisit later.
pub_failed=0
date
pushd ~
touch /cvmfs/mu2e.osgstorage.org/pnfs
PYTHONUNBUFFERED=1 cvmfs-sync root://fndca1.fnal.gov:1095/pnfs/fnal.gov/usr/mu2e/persistent/stash /cvmfs/mu2e.osgstorage.org/pnfs/fnal.gov/usr/mu2e/persistent/stash
popd
