#!/bin/sh

pub_failed=1

function finish_txn {
  if [ $pub_failed -eq 1 ]; then
    cvmfs_server abort -f
    exit 1
  else
    exec cvmfs_server publish -X stash.osgstorage.org
  fi
}

echo "Starting Stash public data update at `date`"

# Periodically, we'll get a "ligo.osgstorage.org is not based on the newest published revision";
# this seems to clear it up.
echo "Aborting any old transaction."
cvmfs_server abort -f stash.osgstorage.org
cvmfs_server transaction stash.osgstorage.org
if [ $? -ne 0 ]; then
  echo "Failed to start transaction."
  exit 3
fi

trap finish_txn EXIT ERR SIGHUP SIGINT SIGTERM

# For now, publish even on failure - we want to publish partial progress.
# May revisit later.
pub_failed=0
date
touch /cvmfs/stash.osgstorage.org/user/bbockelm
pushd ~
PYTHONUNBUFFERED=1 stash_async --delete -n 50 --max-time 600 root://stash.osgconnect.net//user/ /cvmfs/stash.osgstorage.org/user/
popd

